workflows:
  ios-app-store:
    name: Upload build to ASC (debug)

    integrations:
      app_store_connect: "CodeMagic API"

    environment:
      xcode: 16.3
      groups: [appstore_credentials]              # API‑key + CERT_PASSWORD
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME:  "HiddenCameraDetector"

    scripts:
      # ───────────────────────────────────────────────────────────────
      # 0.  Печатаем базовое окружение
      - name: 🔎  Print environment
        script: |
          echo "CI user      : $(whoami)"
          echo "macOS version: $(sw_vers -productVersion)"
          echo "Xcode path   : $(xcode-select -p)"
          echo "Team ID      : 74YTNA35A3"
          echo "Project      : $XCODE_PROJECT"
          echo "Scheme       : $XCODE_SCHEME"

      # 1.  Какие сертификаты реально импортированы в keychain
      - name: 🔎  List certificates
        script: |
          echo "Certificates in Codemagic keychain:"
          keychain list-certificates || true

          echo "Security identities:"
          security find-identity -v -p codesigning || true

      # 2.  Какие provisioning‑profile скачал Codemagic
      - name: 🔎  List profiles
        script: |
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "Profiles at $PROFILE_DIR :"
          ls -l "$PROFILE_DIR" || true

          # выводим BundleID, TeamID, Capabilities каждого профиля
          for f in "$PROFILE_DIR"/*.mobileprovision; do
            [ -e "$f" ] || continue
            echo "----- $(basename "$f") ------------------------------------"
            /usr/bin/security cms -D -i "$f" \
              | /usr/bin/plutil -extract Name xml1 -o - - \
              | xmllint --xpath "string(//string)" - 2>/dev/null
            /usr/bin/security cms -D -i "$f" \
              | /usr/bin/plutil -extract Entitlements xml1 -o - - \
              | xmllint --xpath "//dict/key" - 2>/dev/null | tr '\n' ' '
            echo; echo
          done

      # 3.  Проверяем, что проект видит те же BundleID/SigningStyle
      - name: 🔎  Show build settings
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme "$XCODE_SCHEME" \
                     -showBuildSettings | egrep "DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER|CODE_SIGN_STYLE"

      # 4.  Сборка (без явных override ‑ пусть Xcode сам выбирает профиль)
      - name: Archive & export
        script: |
          set -e
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme  "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -allowProvisioningUpdates \
                     clean archive

          # 4.1  Извлекаем embedded.mobileprovision для анализа
          APP_PATH="$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive/Products/Applications/$XCODE_SCHEME.app"
          if [[ -f "$APP_PATH/embedded.mobileprovision" ]]; then
            echo "🔎  embedded.mobileprovision inside .app:"
            /usr/bin/security cms -D -i "$APP_PATH/embedded.mobileprovision" \
              | /usr/bin/plutil -extract Name xml1 -o - - \
              | xmllint --xpath "string(//string)" -
            echo
          else
            echo "⚠️  embedded.mobileprovision is missing in app bundle"
          fi

          # 4.2  Экспорт IPA
          xcodebuild -exportArchive \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates \
                     -exportPath "$CM_EXPORT_DIR"

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"

    publishing:
      app_store_connect:
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        key_id:    $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store:  false

# Файлы, которые Codemagic должен скачать перед скриптами
code_signing:
  certificates:
    - certificate: Hidden                     # Apple Distribution p12
      password:   $CERT_PASSWORD
  provisioning_profiles:
    - profile: HiddenProfile                  # .mobileprovision c Wi‑Fi capability
      bundle_id: dev.legacy.HiddenCameraDetector
