workflows:
  ios-app-store:
    name: Upload build to ASC

    integrations:
      app_store_connect: "CodeMagic API"

    environment:
      xcode: 16.3
      groups: [appstore_credentials]        # API key + CERT_PASSWORD
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME:  "HiddenCameraDetector"

    scripts:
      # 1️⃣ Создать keychain + импортировать сертификат и профиль
      - name: Init signing assets
        script: |
          keychain initialize               # private keychain
          keychain add-certificates         # возьмёт Hidden.p12 + HiddenProfile

      # 2️⃣ Прописать UUID HiddenProfile во все конфигурации проекта
      - name: Apply provisioning profile
        script: |
          xcode-project use-profiles \
            --project "$XCODE_PROJECT"

      # 3️⃣ Архив + экспорт IPA
      - name: Archive & export
        script: |
          set -e
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme  "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -allowProvisioningUpdates \
                     clean archive

          xcodebuild -exportArchive \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath "$CM_EXPORT_DIR"

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"

    publishing:
      app_store_connect:
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        key_id:    $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store:  false

# ⬇️  Codemagic скачает ФАЙЛЫ отсюда и положит в keychain (без этого шаг add‑certificates ничего не найдёт)
code_signing:
  certificates:
    - certificate: Hidden                  # reference name в UI
      password:   $CERT_PASSWORD
  provisioning_profiles:
    - profile: HiddenProfile               # reference name в UI
      bundle_id: dev.legacy.HiddenCameraDetector
