workflows:
  ios-app-store:
    name: "iOS • Upload build to App Store Connect"

    environment:
      xcode: 16.3
      groups: [appstore_credentials]           # API‑key + p12‑pwd
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME:  "HiddenCameraDetector"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: "dev.legacy.HiddenCameraDetector"   # = Info.plist

    scripts:
      - name: "Archive"
        script: |
          set -e
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme  "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination "generic/platform=iOS" \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -allowProvisioningUpdates \
                     clean archive

      - name: "Export IPA"
        script: |
          xcodebuild -exportArchive \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates \
                     -exportPath "$CM_EXPORT_DIR"

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"

    publishing:
      app_store_connect:
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY   # содержимое .p8
        key_id:    $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store:  false

code_signing:
  certificates:
    - certificate: Hidden           # reference‑name в UI
      password:   $CERT_PASSWORD
  provisioning_profiles:
    - profile: HiddenProfile        # reference‑name в UI
      bundle_id: dev.legacy.HiddenCameraDetector
