workflows:
  ios-app-store:
    name: Upload build to ASC
    integrations:
      app_store_connect: "CodeMagic API"

    environment:
      xcode: 16.3
      groups: [appstore_credentials]          # API‑key + CERT_PASSWORD
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME:  "HiddenCameraDetector"
        TEAM_ID: "74YTNA35A3"
        PROFILE_NAME: "HiddenProfile"         # как отображается в Xcode
        CODE_SIGN_ID: "Apple Distribution"

    scripts:
      - name: Archive & export
        script: |
          set -e
          # 📍 Явно указываем профиль, сертификат и team‑id
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme  "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -allowProvisioningUpdates \
                     DEVELOPMENT_TEAM="$TEAM_ID" \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="$CODE_SIGN_ID" \
                     PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
                     clean archive

          xcodebuild -exportArchive \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates \
                     -exportPath "$CM_EXPORT_DIR"

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"

    publishing:
      app_store_connect:
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        key_id:    $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store:  false

code_signing:
  certificates:
    - certificate: Hidden
      password:   $CERT_PASSWORD
  provisioning_profiles:
    - profile: HiddenProfile
      bundle_id: dev.legacy.HiddenCameraDetector
