workflows:
  ios-app-store:
    name: "iOS • Upload build to App Store Connect"

    # 1. Используем интеграцию Apple Developer Portal, которую вы добавили в UI
    integrations:
      app_store_connect: "CodeMagic API"       # точное имя ключа

    # 2. Среда
    environment:
      xcode: 16.3
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME:  "HiddenCameraDetector"

      ios_signing:                            # автоматический подбор сертификата/профиля
        distribution_type: app_store
        bundle_identifier: "dev.legacy.HiddenCameraDetector"

    # 3. Сборка
    scripts:
      - name: "Archive"
        script: |
          set -e
          xcode-project use-profiles          # подтянуть Hidden.p12 и HiddenProfile.mobileprovision
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme  "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination "generic/platform=iOS" \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -allowProvisioningUpdates archive

      - name: "Export IPA"
        script: |
          xcodebuild -exportArchive \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates \
                     -exportPath "$CM_EXPORT_DIR"

    # 4. Артефакты
    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"

    # 5. Публикация (только загрузка, без TestFlight/Review)
    publishing:
      app_store_connect:
        credentials:
          integration: "CodeMagic API"        # ← ключ наследуется отсюда
        submit_to_testflight: false
        submit_to_app_store:  false
