workflows:
  ios-app-store:
    name: Upload build to ASC — deep debug

    integrations:
      app_store_connect: "CodeMagic API"

    environment:
      xcode: 16.3
      groups: [appstore_credentials]          # API key + CERT_PASSWORD
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME:  "HiddenCameraDetector"

    scripts:
      # 0. Печатаем базовое окружение
      - name: 🔎 Env
        script: |
          echo "macOS   $(sw_vers -productVersion)"
          echo "Xcode   $(xcodebuild -version | head -1)"
          echo "Project $XCODE_PROJECT  Scheme $XCODE_SCHEME"
      - name: 🔎  Check env secrets (masked)
        script: |
          check_var () {
            local name="$1" ; local v="${!name}"
            if [ -z "$v" ]; then
              echo "❌  $name is EMPTY"
            else
              echo "✅  $name length=${#v}  head=${v:0:4}… tail=…${v: -4}"
              echo "$v" | shasum -a 256 | awk '{print "    sha256="$1}'
            fi
          }

          check_var APP_STORE_CONNECT_PRIVATE_KEY
          check_var APP_STORE_CONNECT_KEY_ID
          check_var APP_STORE_CONNECT_ISSUER_ID
          check_var CERT_PASSWORD

      # 1. Список импортированных сертификатов
      - name: 🔎 Certificates
        script: |
          keychain list-certificates || true
          security find-identity -v -p codesigning || true

      # 2. Список профилей
      - name: 🔎 Profiles
        script: |
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          ls -l "$PROFILE_DIR" || true

      # 3. Build settings таргета
      - name: 🔎 Build settings
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme  "$XCODE_SCHEME" \
                     -showBuildSettings | egrep "PRODUCT_BUNDLE_IDENTIFIER|CODE_SIGN_STYLE|DEVELOPMENT_TEAM"

      # 4. Archive + Export
      
      - name: Archive & export
        script: |
          set -e
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme  "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -allowProvisioningUpdates \
                     clean archive

          # Проверяем embedded.mobileprovision
          APP_PATH="$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive/Products/Applications/$XCODE_SCHEME.app"
          if [[ -f "$APP_PATH/embedded.mobileprovision" ]]; then
            echo "embedded.mobileprovision present ✅"
          else
            echo "embedded.mobileprovision missing ⚠️"
          fi

          xcodebuild -exportArchive \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates \
                     -exportPath "$CM_EXPORT_DIR"

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"

    publishing:
      app_store_connect:
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        key_id:    "A2K27N65XP"
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store:  false

code_signing:
  certificates:
    - certificate: Hidden          # убедитесь, что spelling 100 %
      password:   "r2Nf6xSB"
  provisioning_profiles:
    - profile: HiddenProfile
      bundle_id: dev.legacy.HiddenCameraDetector
