workflows:
  ios-app-store:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME: "HiddenCameraDetector"
      xcode: latest
    scripts:
      - name: "Debug: проверить entitlements профиля"
        script: |
          PROFILE_PATH=$(find /Users/builder/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | grep HiddenProfile)
          
          echo "Найден профиль: $PROFILE_PATH"

          if [ -f "$PROFILE_PATH" ]; then
            echo "Расшифровка профиля:"
            security cms -D -i "$PROFILE_PATH" > profile.plist
            plutil -p profile.plist | grep com.apple.developer.networking.wifi-info || echo "Capability НЕ НАЙДЕНА"
          else
            echo "Provisioning profile не найден."
            exit 1
          fi

      - name: Build .ipa
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            -destination generic/platform=iOS \
            archive -archivePath $CM_BUILD_DIR/$XCODE_SCHEME.xcarchive

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/$XCODE_SCHEME.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ExportedIPA

    artifacts:
      - $CM_BUILD_DIR/ExportedIPA/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

code_signing:
  certificates:
    - certificate: Hidden
      password: "vAvdbtoY"
  provisioning_profiles:
    - HiddenCameraDetector: HiddenProfile
