workflows:
  ios-app-store:
    name: Upload build to ASC

    integrations:
      app_store_connect: "CodeMagic API"

    environment:
      xcode: 16.3
      groups: [appstore_credentials]          # API key + CERT_PASSWORD
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME:  "HiddenCameraDetector"

    scripts:
      # 👉 временный диагностический шаг
      - name: List profiles on agent
        script: |
          echo "Profiles downloaded by Codemagic:"
          ls -l "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: Archive & export
        script: |
          set -e
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme  "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -allowProvisioningUpdates \
                     clean archive
          xcodebuild -exportArchive \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates \
                     -exportPath "$CM_EXPORT_DIR"

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"

    publishing:
      app_store_connect:
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        key_id:    $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store:  false

code_signing:
  certificates:
    - certificate: Hidden
      password:   $CERT_PASSWORD
  provisioning_profiles:
    - profile: HiddenProfile
      bundle_id: dev.legacy.HiddenCameraDetector
