workflows:
  ios-app-store:
    name: Upload build to ASC

    integrations:
      app_store_connect: "CodeMagic API"          # ключ в UI

    environment:
      xcode: 16.3
      groups: [appstore_credentials]
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME:  "HiddenCameraDetector"

    scripts:
      - name: "Apply manual signing"
        script: |
          set -e
          xcode-project use-profiles \
            --project "$XCODE_PROJECT" \
            --scheme  "$XCODE_SCHEME" \
            --profile "HiddenProfile"            # reference‑name профиля
          # профилю соответствует сертификат «Hidden» — подтянется автоматически

      - name: "Archive"
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -allowProvisioningUpdates \
                     clean archive

      - name: "Export IPA"
        script: |
          xcodebuild -exportArchive \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath "$CM_EXPORT_DIR"

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"

    publishing:
      app_store_connect:
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        key_id:    $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store:  false

code_signing:
  certificates:
    - certificate: Hidden                         # p12 в UI
      password:   $CERT_PASSWORD
  provisioning_profiles:
    - profile: HiddenProfile                      # .mobileprovision в UI
      bundle_id: dev.legacy.HiddenCameraDetector
