workflows:
  ios-app-store:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME: "HiddenCameraDetector"
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: dev.legacy.HiddenCameraDetector
    scripts:
      - name: Build .ipa
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/$XCODE_SCHEME.xcarchive

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/$XCODE_SCHEME.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ExportedIPA
    artifacts:
      - $CM_BUILD_DIR/ExportedIPA/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
