workflows:
  ios-app-store:
    name: Upload build to ASC

    integrations:
      app_store_connect: "CodeMagic API"

    environment:
      xcode: 16.3
      groups: [appstore_credentials]          # API key + CERT_PASSWORD
      vars:
        XCODE_PROJECT: "HiddenCameraDetector.xcodeproj"
        XCODE_SCHEME:  "HiddenCameraDetector"

    scripts:
      # 1️⃣ создаём временный keychain
      - name: Init keychain
        script: keychain initialize
      
      # 2️⃣ добавляем п12 и .mobileprovision из UI
      - name: Import signing assets
        script: keychain add-certificates     # подтянет Hidden + HiddenProfile

      # 3️⃣ прописываем профиль во все targets
      - name: Apply manual signing
        script: xcode-project use-profiles    # аргументы НЕ нужны

      # 4️⃣ архивируем
      - name: Archive
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme  "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -allowProvisioningUpdates \
                     clean archive

      # 5️⃣ экспортируем IPA
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath "$CM_EXPORT_DIR"

    artifacts:
      - "$CM_EXPORT_DIR/*.ipa"

    publishing:
      app_store_connect:
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        key_id:    $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store:  false

code_signing:
  certificates:
    - certificate: Hidden
      password:   $CERT_PASSWORD
  provisioning_profiles:
    - profile: HiddenProfile
      bundle_id: dev.legacy.HiddenCameraDetector
